// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./core.test.js')
  await import('./input.test.js')
  await import('./select.test.js')
  await import('./confirm.test.js')

  test.resume()
}
